version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  app:
    image: library-app  
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      JWT_SECRET: 

volumes:
  postgres_data: