CREATE TABLE Person (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL UNIQUE,
    birth_year INTEGER NOT NULL CHECK (birth_year > 1900 AND birth_year < EXTRACT(YEAR FROM CURRENT_DATE))
);

CREATE TABLE Book (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL CHECK (year > 0),
    person_id INTEGER REFERENCES Person(id) ON DELETE SET NULL
);